### ISSUE TITLE
andThen's are removed during conversion.

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-codemods/ember-qunit-codemod#196]
before:
```ts
test(....) {
  // ... setup stuff

  andThen(() => ...)
  andThen(() => ...)
}
```
after:
```ts
test(....) {
  // ... setup stuff
}
```

this is especially bad when andThen's contain additional UI interaction as well as numerous assertions :-\

**Comment by NullVoxPopuli** [comment]
looks like this is explicitly for inline andThen`s

**Comment by rwjblue** [comment]
This was fixed by https://github.com/ember-codemods/ember-qunit-codemod/pull/197, @NullVoxPopuli can you confirm and close?

**Comment by NullVoxPopuli** [comment]
I can/did! <3
